CREATE DATABASE IF NOT EXISTS EOL_DB;
USE EOL_DB;

CREATE TABLE IF NOT EXISTS os (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom_os VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS referentiel_eol (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom_os VARCHAR(50) NOT NULL,
    version VARCHAR(20) NOT NULL,
    version_detail VARCHAR(50) NOT NULL UNIQUE,
    date_eol DATE,
    derniere_maj TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(nom_os, version, version_detail) 
);

CREATE TABLE IF NOT EXISTS version (
    id INT AUTO_INCREMENT PRIMARY KEY,
    version VARCHAR(50) NOT NULL,
    version_detail VARCHAR(50),
    total VARCHAR(255),
    ip VARCHAR(50),
    date_eol DATE,
    date_scan_eol TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    os_id INT NOT NULL,
    CONSTRAINT fk_os FOREIGN KEY (os_id) REFERENCES os(id) ON DELETE CASCADE
);
